version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - noctx
    - copyloopvar

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/locplace/scanner

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US

issues:
  exclude-rules:
    - linters:
        - unparam
      text: "always receives"
    - path: _test\.go
      linters:
        - unparam
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
