-- Migration 008: Scanner sessions for multi-instance support
-- Allows multiple scanner instances to use the same token.
-- Each instance gets a unique session that tracks its heartbeats and claimed batches.

-- Step 1: Create scanner_sessions table
-- The session_id is generated by the scanner on startup and sent with each request.
CREATE TABLE scanner_sessions (
    id UUID PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES scanner_clients(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_heartbeat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_scanner_sessions_client ON scanner_sessions(client_id);
CREATE INDEX idx_scanner_sessions_heartbeat ON scanner_sessions(last_heartbeat);

-- Step 2: Add session_id to scan_batches
-- Nullable for backwards compatibility with existing batches.
ALTER TABLE scan_batches ADD COLUMN session_id UUID REFERENCES scanner_sessions(id) ON DELETE SET NULL;

CREATE INDEX idx_batches_session ON scan_batches(session_id) WHERE session_id IS NOT NULL;
